# NumPy `ndarray` Basics

## Table of Contents

1. [The De Facto Standard for Array Data](#1.-The-De-Facto-Standard-for-Array-Data)
2. [Anatomy of an `ndarray`: Structure and Memory](#2.-Anatomy-of-an-`ndarray`:-Structure-and-Memory)
3. [Array Creation and Logical Views (Views vs. Copies)](#3.-Array-Creation-and-Logical-Views-(Views-vs.-Copies))
4. [Aggregations and Axes](#4.-Aggregations-and-Axes)
5. [Broadcasting: The "Stretch" Rule](#5.-Broadcasting:-The-"Stretch"-Rule)
6. [Why Vectorize? The Speed Advantage](#6.-Why-Vectorize?-The-Speed-Advantage)

## 1. The De Facto Standard for Array Data

NumPy is the foundational library for High Performance Computing (HPC) and Machine Learning (ML) in Python. Libraries like PyTorch, Pandas, and Scikit-learn are built upon or mirror the NumPy API. Learning NumPy is essential for mastering the Array Programming paradigm.

NumPy provides the `ndarray` (N-dimensional array), a powerful, high-performance, and uniform container that enables highly efficient memory management, indexing, slicing, and, most importantly, vectorized arithmetic.

In [2]:
import numpy as np

## 2. Anatomy of an `ndarray`: Structure and Memory

Unlike a standard Python list, an `ndarray` is a fixed-size, structured block of contiguous memory. Its efficiency comes from these four key, immutable properties:

- **Data**: A pointer to the memory location holding the elements.
- **dtype**: The data type (e.g., `int32`, `float64`) which is uniform across all elements.
- **Shape**: A tuple defining the size along each dimension (e.g., $(100, 50)$ for 100 rows and 50 columns).
- **Strides**: The number of bytes to step in memory to reach the next element along each dimension—this is how NumPy efficiently handles different shapes and views.

Let's explore these properties by creating a large dataset.

---

**Quick Docs**
- `np.arange(start, stop, step)`: Returns evenly spaced values in the half-open interval $[\text{start}, \text{stop})$.
- `arr.nbytes`: Total bytes consumed by the array's elements (in bytes).
- `arr.ndim`: The number of array dimensions (integer).
- `arr.size`: The total number of elements in the array (integer).
- `arr.shape`: The tuple of array dimensions.


In [3]:
# Use a large number to clearly demonstrate the memory density of ndarrays
N = 50_000_000

In [4]:
# TODO: Create the input data array with the numbers 1 to 50_000_000 (inclusive).
# Hint: np.arange generates values within a half-open interval [start, stop)
arr = np.arange(1, N+1)

In [5]:
# TODO: Calculate how large the array is in GB with nbytes.
# Hint: GB is 1e9 bytes. The .nbytes attribute returns the total bytes consumed by the elements.
# Note: This demonstrates that arrays are dense memory blocks, unlike pointer-heavy Python lists.
arr.nbytes

400000000

In [10]:
print(f"{arr.nbytes:,d}")

400,000,000


In [6]:
# TODO: How many dimensions does the array have? (ndim)
arr.ndim

1

In [8]:
# TODO: How many elements does the array have? (size)
arr.size

50000000

In [11]:
print(f"{arr.size:,d}")

50,000,000


In [9]:
# TODO: What is the shape of the array?
arr.shape

(50000000,)

## 3. Array Creation and Logical Views (Views vs. Copies)

Arrays can logically represent data in many ways (e.g., 1D signal, 2D image, 4D video batch) independent of the underlying physical memory block.

A critical performance feature is that operations like transposing or `reshape` often return a **View** instead of a **Copy**. A View only changes the metadata (`shape` and `strides`) without duplicating the physical data, making these operations nearly instantaneous.

---

**Quick Docs**
- `np.linspace(start, stop, num)`: Returns `num` evenly spaced samples, calculated over the interval $[\text{start}, \text{stop}]$.
- `np.random.default_rng().random(size)`: Returns random floats in $[0.0, 1.0)$. `size` can be a tuple.
- `arr.sort()`: Sorts an array in-place (modifies the original data). Use `np.sort(arr)` to return a sorted copy.
- `arr.reshape(new_shape)`: Returns a View with a new shape. One dimension can be -1, instructing NumPy to calculate the size automatically.
- `np.resize(arr, new_shape)`: Returns a new array with the specified shape. If the new shape is larger, it fills the new elements by repeating the original array.


In [12]:
# TODO: Create a new array with 5_000_000 elements containing equally spaced values between 0 to 1000 (inclusive).
arr = np.linspace(0, 1000, 5_000_000)
arr

array([0.0000000e+00, 2.0000004e-04, 4.0000008e-04, ..., 9.9999960e+02,
       9.9999980e+02, 1.0000000e+03], shape=(5000000,))

In [13]:
# TODO: Create a random array that is 10_000 rows by 5_000 columns.
r, c = 10_000, 5_000
arr = np.random.default_rng().random(r*c).reshape(r, c)
arr

array([[0.07044205, 0.83674796, 0.02715976, ..., 0.18825497, 0.88076385,
        0.01916627],
       [0.96535554, 0.3209304 , 0.38134581, ..., 0.02760354, 0.95064995,
        0.84035546],
       [0.4746358 , 0.07154679, 0.43829204, ..., 0.48874715, 0.58001012,
        0.3289388 ],
       ...,
       [0.54197592, 0.21522581, 0.87956541, ..., 0.68666558, 0.98344439,
        0.75563967],
       [0.73441875, 0.16402227, 0.74207111, ..., 0.46969035, 0.97623738,
        0.46113223],
       [0.64795467, 0.67331091, 0.3295849 , ..., 0.76788   , 0.30420626,
        0.26491042]], shape=(10000, 5000))

In [14]:
# TODO: Sort that array (in-place).
# Note: arr.sort() modifies the array directly, which is typically faster than creating a copy.
arr.sort()

In [15]:
# TODO: Reshape the array to have the last dimension of length 5.
# Ensure that the operation only changes the logical view without duplicating the physical data pointer.
# Hint: You can use -1 for one dimension to let NumPy automatically calculate the size based on the total elements.
arr_new = arr.reshape(-1, 5)
arr_new

array([[1.42765873e-06, 1.15089432e-04, 1.82418763e-04, 3.42187965e-04,
        6.05588674e-04],
       [7.14002871e-04, 7.52244152e-04, 1.22703709e-03, 1.40071675e-03,
        1.64176705e-03],
       [2.10285965e-03, 2.33071026e-03, 2.51534034e-03, 2.51763970e-03,
        2.65459847e-03],
       ...,
       [9.96714213e-01, 9.97009526e-01, 9.97041012e-01, 9.97230603e-01,
        9.97326350e-01],
       [9.97634485e-01, 9.97709405e-01, 9.97990746e-01, 9.98110342e-01,
        9.98184565e-01],
       [9.98331133e-01, 9.98427892e-01, 9.98721571e-01, 9.99602274e-01,
        9.99635981e-01]], shape=(10000000, 5))

## 4. Aggregations and Axes

When performing aggregations (like `sum`, `mean`, `max`), you must specify the **Axis** you want to collapse (or reduce) the array along.

- **Axis 0**: The first dimension (often rows in 2D). Aggregating across Axis 0 produces a result for each column.
- **Axis 1**: The second dimension (often columns in 2D). Aggregating across Axis 1 produces a result for each row.

---

**Quick Docs**
- `np.sum(a, axis=None)`: Sum of array elements over a given axis.
  - `axis=0`: Collapse the rows (sum vertical columns).
  - `axis=1`: Collapse the columns (sum horizontal rows).


In [16]:
# TODO: Find the sum of each row in the reshaped array (arr_new) above.
# Hint: To sum the row's content, we must reduce across the columns.
arr_sum = np.sum(arr_new, 1)
arr_sum

array([1.24671249e-03, 5.73576791e-03, 1.21211484e-02, ...,
       4.98532170e+00, 4.98962954e+00, 4.99471885e+00], shape=(10000000,))

## 5. Broadcasting: The "Stretch" Rule

Broadcasting is NumPy's mechanism for performing arithmetic between arrays of different shapes. If dimensions don't match, NumPy attempts to "stretch" the smaller array to match the larger one.

**The Compatibility Rule:** Two dimensions are compatible when:
1. They are equal, or
2. One of them is 1.

If a dimension is 1, NumPy logically copies that single value across the dimension to match the other array's shape **without allocating any new memory**.

---

**Quick Docs**
- **Arithmetic Operators** (`/`, `*`, `+`, `-`): These operate element-wise. Broadcasting occurs if shapes are different but compatible.
- `np.allclose(a, b)`: Returns `True` if two floating-point arrays are element-wise equal within a tolerance. Essential for comparisons instead of using `==`.


In [19]:
# TODO: Normalize each row of the 2D array (arr_new) by dividing by the sum you just computed (arr_sum).
# Hint: 'arr_new' is (M, N) and 'arr_sum' is (M,). To successfully divide, you may need to reshape 'arr_sum' to (M, 1)
# so that broadcasting can stretch it across the N columns.

print(arr_new.shape)
print(arr_sum.shape)

arr_normalized = arr_new / np.reshape(arr_sum, [-1, 1])
arr_normalized

(10000000, 5)
(10000000,)


array([[0.00114514, 0.09231433, 0.14631983, 0.27447224, 0.48574846],
       [0.12448252, 0.13114968, 0.21392726, 0.24420736, 0.28623317],
       [0.17348683, 0.19228461, 0.20751667, 0.20770637, 0.21900552],
       ...,
       [0.19992977, 0.199989  , 0.19999532, 0.20003335, 0.20005256],
       [0.19994159, 0.19995661, 0.20001299, 0.20003696, 0.20005184],
       [0.19987734, 0.19989672, 0.19995551, 0.20013184, 0.20013859]],
      shape=(10000000, 5))

In [37]:
# EXTRA CREDIT: Prove that your normalized array is actually normalized.
# Hint: If normalized correctly, the sum of every row should now be 1.0.
# Check if the new row sums are close to 1.0 using np.allclose.

np.allclose(np.sum(arr_normalized, 1), 1.0)

True

## 6. Why Vectorize? The Speed Advantage

The entire Array Programming paradigm hinges on **Vectorization**.

Why use complex shapes and broadcasting instead of simple Python `for` loops?

NumPy's array functions are implemented in highly optimized native code (C/C++, Fortran). An operation like `A + A**2`, where `A` is a massive `ndarray`, is often $\mathbf{100\times}$ faster than performing the equivalent element-wise operation using explicit Python loops.

**Always choose a vectorized NumPy function or operator over a manual Python loop.**